[package]
name = "block_util"
version = "0.1.0"
authors = ["The Cloud Hypervisor Authors"]
edition = "2018"

[features]
default = []
io_uring = []

[dependencies]
io-uring = "0.5.1"
libc = "0.2.99"
log = "0.4.14"
qcow = { path = "../qcow" }
thiserror = "1.0.26"
versionize = "0.1.6"
versionize_derive = "0.1.4"
virtio-bindings = { version = "0.1.0", features = ["virtio-v5_0_0"] }
vm-memory = { version = "0.6.0", features = ["backend-mmap", "backend-atomic", "backend-bitmap"] }
vm-virtio = { path = "../vm-virtio" }
vmm-sys-util = "0.8.0"

