[package]
name = "test_infra"
version = "0.1.0"
authors = ["The Cloud Hypervisor Authors"]
edition = "2021"

[dependencies]
dirs = "5.0.0"
epoll = "4.3.3"
libc = "0.2.147"
once_cell = "1.19.0"
serde = { version = "1.0.168", features = ["rc", "derive"] }
serde_json = "1.0.109"
ssh2 = { version = "0.9.4", features = ["vendored-openssl"] }
vmm-sys-util = "0.12.0"
wait-timeout = "0.2.0"
