[package]
authors = ["The Cloud Hypervisor Authors"]
edition = "2021"
name = "test_infra"
version = "0.1.0"

[dependencies]
dirs = "5.0.1"
epoll = "4.3.3"
libc = "0.2.158"
once_cell = "1.19.0"
serde = { version = "1.0.208", features = ["derive", "rc"] }
serde_json = "1.0.120"
ssh2 = { version = "0.9.4", features = ["vendored-openssl"] }
vmm-sys-util = { workspace = true }
wait-timeout = "0.2.0"
