[package]
name = "vhost_user_backend"
version = "0.1.0"
authors = ["The Cloud Hypervisor Authors"]
edition = "2018"

[features]
default = []
pci_support = ["vm-virtio/pci_support"]
mmio_support = ["vm-virtio/mmio_support"]

[dependencies]
epoll = "4.1.0"
libc = "0.2.65"
vm-memory = { git = "https://github.com/rust-vmm/vm-memory" } 
vm-virtio = { path = "../vm-virtio" }
vmm-sys-util = "0.2.0"

[dependencies.vhost_rs]
path = "../vhost_rs"
features = ["vhost-user-slave"]

