[package]
name = "vm-allocator"
version = "0.1.0"
authors = ["The Chromium OS Authors"]
edition = "2021"

[dependencies]
libc = "0.2.153"
vm-memory = "0.14.1"
thiserror = "1.0.52"

[target.'cfg(target_arch = "aarch64")'.dependencies]
arch = { path = "../arch" }
