[package]
authors = ["The Chromium OS Authors"]
edition.workspace = true
name = "vm-allocator"
version = "0.1.0"

[features]
default = []
kvm = ["arch/kvm"]

[dependencies]
libc = { workspace = true }
vm-memory = { workspace = true }

[target.'cfg(any(target_arch = "aarch64", target_arch = "riscv64"))'.dependencies]
arch = { path = "../arch" }
