[package]
name = "vhost_user_block"
version = "0.1.0"
authors = ["The Cloud Hypervisor Authors"]
edition = "2021"

[dependencies]
block_util = { path = "../block_util" }
clap = { version = "3.1.18", features = ["wrap_help","cargo"] }
env_logger = "0.9.0"
epoll = "4.3.1"
libc = "0.2.125"
log = "0.4.17"
option_parser = { path = "../option_parser" }
qcow = { path = "../qcow" }
vhost = { version = "0.4.0", features = ["vhost-user-slave"] }
vhost-user-backend = { git = "https://github.com/rust-vmm/vhost-user-backend", rev = "14f58eda14076e973704d4f904850be1146fbb05" }
virtio-bindings = "0.1.0"
vm-memory = "0.8.0"
vmm-sys-util = "0.9.0"

[build-dependencies]
clap = { version = "3.1.18", features = ["cargo"] }
