[package]
authors = ["The Cloud Hypervisor Authors"]
edition.workspace = true
license = "Apache-2.0"
name = "api_client"
version = "0.1.0"

[dependencies]
thiserror = { workspace = true }
vmm-sys-util = { workspace = true }

[lints]
workspace = true
