[package]
authors = ["The Cloud Hypervisor Authors"]
edition = "2021"
name = "virtio-devices"
version = "0.1.0"

[features]
default = []
sev_snp = ["mshv-ioctls"]

[dependencies]
anyhow = "1.0.94"
arc-swap = "1.7.1"
block = { path = "../block" }
byteorder = "1.5.0"
epoll = "4.3.3"
event_monitor = { path = "../event_monitor" }
libc = "0.2.167"
log = "0.4.22"
mshv-ioctls = { workspace = true, optional = true }
net_gen = { path = "../net_gen" }
net_util = { path = "../net_util" }
pci = { path = "../pci" }
rate_limiter = { path = "../rate_limiter" }
seccompiler = { workspace = true }
serde = { version = "1.0.208", features = ["derive"] }
serde_json = { workspace = true }
serde_with = { version = "3.9.0", default-features = false, features = [
  "macros",
] }
serial_buffer = { path = "../serial_buffer" }
thiserror = "2.0.6"
vhost = { workspace = true, features = [
  "vhost-kern",
  "vhost-user-backend",
  "vhost-user-frontend",
  "vhost-vdpa",
] }
virtio-bindings = { workspace = true, features = ["virtio-v5_0_0"] }
virtio-queue = { workspace = true }
vm-allocator = { path = "../vm-allocator" }
vm-device = { path = "../vm-device" }
vm-memory = { workspace = true, features = [
  "backend-atomic",
  "backend-bitmap",
  "backend-mmap",
] }
vm-migration = { path = "../vm-migration" }
vm-virtio = { path = "../vm-virtio" }
vmm-sys-util = { workspace = true }
