[package]
authors = ["The Cloud Hypervisor Authors"]
edition = "2021"
name = "virtio-devices"
version = "0.1.0"

[features]
default = []
sev_snp = ["mshv-ioctls"]

[dependencies]
anyhow = "1.0.86"
arc-swap = "1.7.1"
block = { path = "../block" }
byteorder = "1.5.0"
epoll = "4.3.3"
event_monitor = { path = "../event_monitor" }
libc = "0.2.155"
log = "0.4.22"
mshv-ioctls = { git = "https://github.com/rust-vmm/mshv", tag = "v0.2.0", optional = true }
net_gen = { path = "../net_gen" }
net_util = { path = "../net_util" }
pci = { path = "../pci" }
rate_limiter = { path = "../rate_limiter" }
seccompiler = "0.4.0"
serde = { version = "1.0.208", features = ["derive"] }
serde_json = "1.0.120"
serde_with = { version = "3.9.0", default-features = false, features = [
  "macros",
] }
serial_buffer = { path = "../serial_buffer" }
thiserror = "1.0.62"
vhost = { version = "0.11.0", features = [
  "vhost-kern",
  "vhost-user-backend",
  "vhost-user-frontend",
  "vhost-vdpa",
] }
virtio-bindings = { version = "0.2.2", features = ["virtio-v5_0_0"] }
virtio-queue = "0.12.0"
vm-allocator = { path = "../vm-allocator" }
vm-device = { path = "../vm-device" }
vm-memory = { version = "0.14.1", features = [
  "backend-atomic",
  "backend-bitmap",
  "backend-mmap",
] }
vm-migration = { path = "../vm-migration" }
vm-virtio = { path = "../vm-virtio" }
vmm-sys-util = "0.12.1"
