[package]
name = "tracer"
version = "0.1.0"
authors = ["The Cloud Hypervisor Authors"]
edition = "2021"

[dependencies]
libc = "0.2.134"
log = "0.4.17"
once_cell = "1.12.0"
serde = { version = "1.0.145", features = ["rc", "derive"] }
serde_json = "1.0.86"

[features]
tracing = []
