[package]
authors = ["The Cloud Hypervisor Authors"]
edition = "2021"
name = "tracer"
version = "0.1.0"

[dependencies]
libc = "0.2.167"
log = "0.4.22"
once_cell = "1.20.2"
serde = { version = "1.0.208", features = ["derive", "rc"] }
serde_json = { workspace = true }

[features]
tracing = []
