[package]
authors = ["The Cloud Hypervisor Authors"]
edition = "2021"
name = "tracer"
version = "0.1.0"

[dependencies]
libc = "0.2.158"
log = "0.4.22"
once_cell = "1.19.0"
serde = { version = "1.0.208", features = ["derive", "rc"] }
serde_json = "1.0.120"

[features]
tracing = []
