[package]
name = "vm-migration"
version = "0.1.0"
authors = ["The Cloud Hypervisor Authors"]
edition = "2021"

[dependencies]
anyhow = "1.0.75"
thiserror = "1.0.40"
serde = { version = "1.0.168", features = ["rc", "derive"] }
serde_json = "1.0.107"
versionize = "0.1.10"
versionize_derive = "0.1.4"
vm-memory = { version = "0.13.1", features = ["backend-mmap", "backend-atomic"] }
