[package]
name = "vm-migration"
version = "0.1.0"
authors = ["The Cloud Hypervisor Authors"]
edition = "2018"

[dependencies]
anyhow = "1.0.42"
thiserror = "1.0.26"
serde = { version = "1.0.127", features = ["rc"] }
serde_derive = "1.0.127"
serde_json = "1.0.66"
versionize = "0.1.6"
versionize_derive = "0.1.4"
vm-memory = { version = "0.6.0", features = ["backend-mmap", "backend-atomic"] }
