[package]
name = "vm-migration"
version = "0.1.0"
authors = ["The Cloud Hypervisor Authors"]
edition = "2021"

[dependencies]
anyhow = "1.0.57"
thiserror = "1.0.31"
serde = { version = "1.0.136", features = ["rc"] }
serde_derive = "1.0.136"
serde_json = "1.0.79"
versionize = "0.1.6"
versionize_derive = "0.1.4"
vm-memory = { version = "0.7.0", features = ["backend-mmap", "backend-atomic"] }
