[package]
name = "vm-migration"
version = "0.1.0"
authors = ["The Cloud Hypervisor Authors"]
edition = "2021"

[dependencies]
anyhow = "1.0.64"
thiserror = "1.0.33"
serde = { version = "1.0.144", features = ["rc", "derive"] }
serde_json = "1.0.85"
versionize = "0.1.6"
versionize_derive = "0.1.4"
vm-memory = { version = "0.8.0", features = ["backend-mmap", "backend-atomic"] }
