[package]
authors = ["The Cloud Hypervisor Authors"]
edition = "2021"
name = "vm-migration"
version = "0.1.0"

[dependencies]
anyhow = "1.0.94"
serde = { version = "1.0.208", features = ["derive", "rc"] }
serde_json = { workspace = true }
thiserror = "2.0.6"
vm-memory = { workspace = true, features = ["backend-atomic", "backend-mmap"] }
