[package]
name = "vm-migration"
version = "0.1.0"
authors = ["The Cloud Hypervisor Authors"]
edition = "2021"

[dependencies]
anyhow = "1.0.79"
thiserror = "1.0.52"
serde = { version = "1.0.196", features = ["rc", "derive"] }
serde_json = "1.0.109"
versionize = "0.2.0"
versionize_derive = "0.1.6"
vm-memory = { version = "0.14.0", features = ["backend-mmap", "backend-atomic"] }
