[package]
name = "performance-metrics"
version = "0.1.0"
authors = ["The Cloud Hypervisor Authors"]
edition = "2018"
build = "build.rs"

[dependencies]
clap = { version = "3.1.3", features = ["wrap_help","cargo"] }
dirs = "4.0.0"
serde = { version = "1.0.136", features = ["rc"] }
serde_derive = "1.0.136"
serde_json = "1.0.78"
test_infra = { path = "../test_infra" }
thiserror = "1.0.30"
wait-timeout = "0.2.0"

[build-dependencies]
clap = { version = "3.1.3", features = ["wrap_help"] }
