[package]
name = "performance-metrics"
version = "0.1.0"
authors = ["The Cloud Hypervisor Authors"]
edition = "2021"
build = "build.rs"

[dependencies]
clap = { version = "3.2.7", features = ["wrap_help","cargo"] }
dirs = "4.0.0"
serde = { version = "1.0.137", features = ["rc", "derive"] }
serde_json = "1.0.81"
test_infra = { path = "../test_infra" }
thiserror = "1.0.31"
wait-timeout = "0.2.0"

[build-dependencies]
clap = { version = "3.2.7", features = ["cargo"] }
