[package]
authors = ["The Cloud Hypervisor Authors"]
build = "../build.rs"
edition = "2021"
name = "performance-metrics"
version = "0.1.0"

[dependencies]
clap = { workspace = true, features = ["wrap_help"] }
dirs.workspace = true
serde = { workspace = true, features = ["derive", "rc"] }
serde_json = { workspace = true }
test_infra = { path = "../test_infra" }
thiserror = { workspace = true }
wait-timeout.workspace = true
