[package]
name = "performance-metrics"
version = "0.1.0"
authors = ["The Cloud Hypervisor Authors"]
edition = "2021"
build = "build.rs"

[dependencies]
clap = { version = "4.0.29", features = ["wrap_help","cargo"] }
dirs = "4.0.0"
serde = { version = "1.0.147", features = ["rc", "derive"] }
serde_json = "1.0.87"
test_infra = { path = "../test_infra" }
thiserror = "1.0.37"
wait-timeout = "0.2.0"

[build-dependencies]
clap = { version = "4.0.29", features = ["cargo"] }
