[package]
name = "performance-metrics"
version = "0.1.0"
authors = ["The Cloud Hypervisor Authors"]
edition = "2021"
build = "../build.rs"

[dependencies]
argh = "0.1.9"
dirs = "5.0.0"
serde = { version = "1.0.151", features = ["rc", "derive"] }
serde_json = "1.0.95"
test_infra = { path = "../test_infra" }
thiserror = "1.0.39"
wait-timeout = "0.2.0"
