[package]
name = "event_monitor"
version = "0.1.0"
authors = ["The Cloud Hypervisor Authors"]
edition = "2018"

[dependencies]
libc = "0.2.98"
serde = { version = "1.0.127", features = ["rc"] }
serde_derive = "1.0.127"
serde_json = "1.0.66"
