[package]
authors = ["The Cloud Hypervisor Authors"]
edition = "2021"
name = "event_monitor"
version = "0.1.0"

[dependencies]
flume = "0.11.0"
libc = "0.2.158"
once_cell = "1.20.1"
serde = { version = "1.0.208", features = ["derive", "rc"] }
serde_json = "1.0.120"
