[package]
authors = ["The Cloud Hypervisor Authors"]
edition = "2021"
name = "event_monitor"
version = "0.1.0"

[dependencies]
flume.workspace = true
libc.workspace = true
serde = { workspace = true, features = ["derive", "rc"] }
serde_json = { workspace = true }
