[package]
authors = ["Microsoft Authors"]
edition = "2021"
license = "Apache-2.0"
name = "tpm"
version = "0.1.0"

[dependencies]
anyhow = "1.0.81"
libc = "0.2.153"
log = "0.4.21"
net_gen = { path = "../net_gen" }
thiserror = { workspace = true }
vmm-sys-util = { workspace = true }
