[package]
name = "tpm"
edition = "2021"
authors = ["Microsoft Authors"]
license = "Apache-2.0"
version = "0.1.0"

[dependencies]
anyhow = "1.0.66"
byteorder = "1.4.3"
libc = "0.2.138"
log = "0.4.17"
thiserror = "1.0.37"
vmm-sys-util = "0.11.0"
