[package]
name = "qcow"
version = "0.1.0"
authors = ["The Chromium OS Authors"]
edition = "2018"
license = "BSD-3-Clause"

[lib]
path = "src/qcow.rs"

[dependencies]
byteorder = "1.3.4"
libc = "0.2.84"
log = "0.4.14"
remain = "0.2.2"
vmm-sys-util = ">=0.3.1"

[dev-dependencies]
tempfile = "3.2.0"
